@startuml
!theme plain
start
:Przekaż odnośnik do repozytorium kodu źródłowego zadania;
:Poleć badanemu uruchomienie projektu w IDE;
:Wyjaśnij problem rozwiązywany przez program;
:Wyjaśnij interfejsy i ich metody;
:Wyjaśnij implementacje InMemoryBus i RegisteredConsumers;
if (Badany ma pytania do powyższych?) then (tak)
    if (Pytanie odnosi się do wyjaśnionej części?) then (tak)
    :Wyjaśnij niejasny obszar;
    else (nie)
    :Pomiń pytanie;
    endif
    else (nie)
endif
:Poleć badanemu uruchomienie zestawu testów;
if (Testy nie uruchamiają się bądź kończą się błędem?) then (tak)
:Wraz z badanym napraw problem środowiska uruchomieniowego;
else (nie)
endif
(A)
@enduml