@startuml
!theme plain
(A)
:Poleć badanemu odblokować testy i uruchomić je;
:Wyjaśnij testy jednostkowe,
 opisz słownie wymagania;
:Poleć badanemu rozpocząć zadanie,
 zarejestruj czas jego rozpoczęcia;
:Poczekaj, aż badany uruchomi zestaw
 testów, który zakończy się skucesem;
:Zarejestruj czas zakończenia zadania;
(B)
@enduml